"""Node identity — the per-machine Ed25519 keypair (FOUNDATION Part 3).

Two identities with different lifetimes, deliberately separate:

- **Node** (this module): which machine is this. An Ed25519 keypair under
  ``~/.prometheus/node/``, generated at first run, never copied to another
  machine. The base64 public key IS the node ID.
- **Instance** (the vault marker, ``config/vault_marker.py``): which
  deployment is this. A UUID that travels with the vault.

Binding rules from the spec, restated where they are enforced:

1. The key is identity, never encryption — nothing here encrypts anything,
   and losing the key can never make local data unreadable.
2. The key is never the sole proof of anything — nothing consumes it yet
   beyond display on ``/api/status``.
3. Identity is not derived from hardware — a generated key, so a GPU swap
   changes nothing.
4. Nothing is transmitted without opt-in — the keypair is inert local state.

Source: Prometheus (OAra Labs)
License: MIT
"""

from __future__ import annotations

import base64
import logging
import os
from dataclasses import dataclass
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from prometheus.config.paths import get_node_dir

logger = logging.getLogger(__name__)

NODE_KEY_FILENAME = "node.key"
NODE_PUB_FILENAME = "node.pub"


@dataclass(frozen=True)
class NodeIdentity:
    pubkey: str  # base64 of the raw 32-byte Ed25519 public key — the node ID


def _pub_b64(private_key: Ed25519PrivateKey) -> str:
    raw = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return base64.b64encode(raw).decode("ascii")


def ensure_node_identity() -> NodeIdentity:
    """Load the node keypair, generating it on first run. Idempotent.

    An existing ``node.key`` is NEVER regenerated — regeneration is a new
    identity, and identity changes are never a side effect. A missing or
    stale ``node.pub`` beside a valid key is self-healed by re-deriving it,
    because the public half is a projection of the private half, not state
    of its own.
    """
    node_dir = get_node_dir()
    key_path = node_dir / NODE_KEY_FILENAME
    pub_path = node_dir / NODE_PUB_FILENAME

    if key_path.exists():
        try:
            private_key = serialization.load_pem_private_key(
                key_path.read_bytes(), password=None
            )
        except (ValueError, TypeError) as exc:
            raise RuntimeError(
                f"{key_path} exists but cannot be loaded ({exc}) — refusing "
                "to regenerate over it. Regeneration is a NEW identity and "
                "never happens implicitly; move the file aside deliberately "
                "if this machine should re-key."
            ) from exc
        if not isinstance(private_key, Ed25519PrivateKey):
            raise RuntimeError(
                f"{key_path} exists but is not an Ed25519 private key — "
                "refusing to touch it. A node key is never regenerated in "
                "place; move the file aside deliberately if it is wrong."
            )
        pubkey = _pub_b64(private_key)
        on_disk = pub_path.read_text().strip() if pub_path.exists() else None
        if on_disk != pubkey:
            pub_path.write_text(pubkey + "\n")
            logger.info(
                "node.pub %s — re-derived from node.key",
                "was missing" if on_disk is None else "disagreed with node.key",
            )
        return NodeIdentity(pubkey=pubkey)

    private_key = Ed25519PrivateKey.generate()
    pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    # O_EXCL: two processes racing first-run must not both mint an identity;
    # the loser reloads the winner's key. 0600 from the first byte — the
    # file never exists world-readable, even transiently.
    try:
        fd = os.open(key_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        return ensure_node_identity()
    with os.fdopen(fd, "wb") as fh:
        fh.write(pem)
    pubkey = _pub_b64(private_key)
    pub_path.write_text(pubkey + "\n")
    logger.info("Node identity generated: %s… (%s)", pubkey[:12], key_path)
    return NodeIdentity(pubkey=pubkey)


def get_node_pubkey() -> str | None:
    """Read the node ID without generating one. ``None`` before first run.

    Read path only: telemetry and ``/api/status`` call this, and neither
    minting an identity as a side effect of a status poll nor of a trace
    write would be an identity "generated at first run" — it would be one
    generated by whoever asked first.
    """
    pub_path = get_node_dir() / NODE_PUB_FILENAME
    if not pub_path.exists():
        return None
    value = pub_path.read_text().strip()
    return value or None


# ---------------------------------------------------------------------------
# Process-pinned instance identity (read from the vault marker at startup).
#
# Same pattern as set_vault_root/get_vault_root: the daemon resolves it once
# after the marker check and pins it; /api/status reads it back without
# re-reading the vault on every poll. None = no adopted vault this boot.
# ---------------------------------------------------------------------------

_instance_id: str | None = None


def set_instance_id(instance_id: str | None) -> None:
    global _instance_id
    _instance_id = instance_id


def get_instance_id() -> str | None:
    return _instance_id
