#!/usr/bin/env python3
"""Write a harvest-corpus taskset YAML (flywheel corpus).

    uv run python scripts/gen_harvest_corpus.py --per-shape 25 \
        --out gym/tasksets/harvest-v1.yaml

Deterministic: same --per-shape → byte-identical YAML. The generated taskset
targets wrap-prone shapes with distinct scalar values so a --harvest gym run
accumulates DISTINCT training pairs (see src/prometheus/gym/corpus.py).
"""

import argparse
import sys
from pathlib import Path

import yaml

from prometheus.gym.corpus import generate_harvest_corpus


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a harvest-corpus taskset")
    ap.add_argument("--per-transition", type=int, default=20,
                    help="max tasks per transition type (default 20)")
    ap.add_argument("--out", default="gym/tasksets/harvest-v1.yaml")
    args = ap.parse_args()

    corpus = generate_harvest_corpus(args.per_transition)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# GENERATED by scripts/gen_harvest_corpus.py "
        f"(--per-transition {args.per_transition}) — do not hand-edit; regenerate.\n"
        "# Harvest corpus: wrap-prone shapes × distinct values → distinct pairs.\n"
    )
    out.write_text(header + yaml.safe_dump(corpus, sort_keys=False))
    print(f"wrote {len(corpus['tasks'])} tasks → {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
